# Generated by Django 3.0.1 on 2020-01-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.TextField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PanelProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('L', 'LetterProvider'), ('A', 'ArrayProvider'), ('N', 'NodeProvider')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('secret_code', models.TextField()),
                ('external_id', models.ManyToManyField(to='main.Country')),
                ('panel_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PanelProvider')),
                ('parent_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TargetGroup')),
            ],
        ),
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country')),
                ('panel_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PanelProvider')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('secret_code', models.TextField()),
                ('external_id', models.ManyToManyField(to='main.LocationGroup')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='panel_provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PanelProvider'),
        ),
    ]
